name: Build&Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Checkout
      uses: actions/checkout@v2
    - name: SonarScanner install
      run: dotnet tool install --global dotnet-sonarscanner
    - name: SonarScanner run
      run: dotnet sonarscanner begin /o:raiffeisen-dgtl /k:Raiffeisen-DGTL_ViennaNET /d:sonar.login=${{ secrets.SONAR_TOKEN }} /d:sonar.host.url=https://sonarcloud.io /d:sonar.verbose=true /d:sonar.cs.nunit.reportsPaths="**/TestResult/TestResults*.xml" /d:sonar.cs.opencover.reportsPaths="**/TestResult/coverage.opencover.xml"
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet test --no-build --filter "TestCategory=Unit" --logger "nunit;LogFilePath=TestResult/TestResult-{assembly}.xml" /p:CollectCoverage=true /p:CoverletOutputFormat=\"opencover\" /p:CoverletOutput=TestResult/
    - name: Sonar End
      run: dotnet sonarscanner end /d:sonar.login=${{ secrets.SONAR_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
